---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  python:
    - six
    - psutil

options:
  package_manager_path: /usr/bin/dnf

images:
  base_image:
    name: docker.io/redhat/ubi9:latest
