---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core==2.14.4
  ansible_runner:
    package_pip: ansible-runner
  python:
    - six
    - psutil

images:
  base_image:
    name: docker.io/redhat/ubi9:latest
