---
- name: Compliance DISA STIG
  hosts: localhost
  tasks:
    - name: Generate a new message
      ansible.builtin.set_fact:
        message: 'Compliance DISA STIG'

    - name: Display message
      ansible.builtin.debug:
        msg: "{{ message }}"
